### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by psolymos** [ABbiodiversity/abmidata#1]
- [x] Add initial script
- [x] Transform script into R package
- [ ] ~~Implement token based auth~~
- [x] Review table list (remove stale endpoints)
- [x] Add documentation
- [ ] ~~Make it a CRAN package~~
